import = ["/home/skulikov/.config/alacritty/rose-pine/rose-pine.toml"]
#import = ["/home/skulikov/.config/alacritty/rose-pine/rose-pine-dawn.yml"]
live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = false

[cursor]
blink_interval = 500

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.bold]
family = "JetBrains Mono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono Nerd Font"
style = "BoldItalic"

[font.italic]
family = "JetBrains Mono Nerd Font"
style = "MediumItalic"

[font.normal]
family = "JetBrains Mono Nerd Font"
style = "Medium"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true

[shell]
program = "/bin/zsh"

[window]
decorations = "None"

[window.padding]
x = 10
y = 10

[window.dimensions]
columns = 136
lines = 34

# [window.position]
# x = 100
# y = 100
# doesn't work on Wyland
# workaround: gsettings set org.gnome.mutter center-new-windows true
